print('===== DESAFIO 026 =====')
frase = str(input('Digite uma frase:')).strip().upper()
print('A letra "A" aparece {} vezes'.format(frase.count('A')))
print('A primeira letra ''A'' apareceu{}.'.format(frase.find('A')+1))
print('A ultima letra "A" apareceu na {}'.format(frase.rfind('A')+1))
